version: '3.8'
services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    ports:
      - "8000:8000"
    networks:
      - app_network
    environment:
      - DEBUG=1
      - SECRET_KEY=your_secret_key
      - ALLOWED_HOSTS=*
      - DATABASE_URL=postgres://user:password@db:5432/db_name
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_app

    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/react
      - /react/node_modules
    networks:
      - app_network
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network


  nginx:
    image: nginx:stable-alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network
    depends_on:
      - backend
      - frontend

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
